//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreAdmissionList
    {
        public int ApplicantId { get; set; }
        public string ApplicantNo { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string OtherNames { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string ExamNo { get; set; }
        public string NationalityID { get; set; }
        public string StateOfOriginID { get; set; }
        public string HomeTown { get; set; }
        public string ClassAdmittedID { get; set; }
        public string ExamBatchNo { get; set; }
        public string Photo { get; set; }
    }
}
