//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OtherNames { get; set; }
        public string Gender { get; set; }
        public string PhotoID { get; set; }
        public string DateOfBirth { get; set; }
        public string BirthPace { get; set; }
        public string Religion { get; set; }
        public string NationalityID { get; set; }
        public string StateOfOriginID { get; set; }
        public string LGAOfOriginID { get; set; }
        public string HomeTown { get; set; }
        public string EntryModeID { get; set; }
        public string AdmissionNo { get; set; }
        public string dateAdmitted { get; set; }
        public string ClassAdmittedID { get; set; }
        public string CurrentClassID { get; set; }
        public string CurrentTermID { get; set; }
        public string StudentCategoryID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string CountryOfResidenceID { get; set; }
        public string StateOfResidenceID { get; set; }
        public string LGAOfResidenceID { get; set; }
        public string CityOfResidence { get; set; }
        public string GuardianID { get; set; }
        public string Status { get; set; }
        public string ID { get; set; }
    }
}
